apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-server-wazuh.fullname" . }}
  labels:
    {{- include "mcp-server-wazuh.labels" . | nindent 4 }}
type: Opaque
stringData:
  WAZUH_API_USERNAME: {{ .Values.wazuh.api.username | quote }}
  WAZUH_API_PASSWORD: {{ .Values.wazuh.api.password | quote }}
  WAZUH_INDEXER_USERNAME: {{ .Values.wazuh.indexer.username | quote }}
  WAZUH_INDEXER_PASSWORD: {{ .Values.wazuh.indexer.password | quote }}
